### ISSUE TITLE
SRI Support via Manifest File

### ISSUE THREAD

**Issue by chez14** [mjhoy/axum-inertia#19]
Hi, is it possible to add SRI context to the `<link ...>` and `<script ...>` when `integrity` hash is provided on the manifest file?

The `integrity` is currently provided via [`vite-plugin-manifest-sri` plugin](https://www.npmjs.com/package/vite-plugin-manifest-sri).

Thank you!

**Comment by mjhoy** [comment]
Interesting, tried to read a little about this and I'm a little confused what `axum-inertia` should do here for this. I haven't used that plugin. Do you have a explanation? Thanks!

**Comment by chez14** [comment]
Hi @mjhoy, sorry for the delayed response.

Ah I think I should have added examples to better explain it... so what the plugin does is adding "integrity" hash on the manifest file, something looked like `sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC`. This value can be forwarded to `integrity` attributes on `<script...>` and `<link...>` elements to let browser verifies for its integrity ([reference](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#how_browsers_handle_subresource_integrity)).

With this, I kinda hope `axum-inertia` able to use this value so that all `<script...>` and `<link...>` elements has this `integrity` value added to them, just like what [Laravel does](https://laravel.com/docs/11.x/vite#subresource-integrity-sri).

I'll try to send a sample manifest file to add more information on what the plugin actually do.

**Comment by mjhoy** [comment]
Gotcha. So `axum-inertia` would parse that value out of the manifest? Definitely seems doable.

**Comment by chez14** [comment]
Sorry for the delayed response, here are the sample `manifest.json` from vite that have [`vite-plugin-manifest-sri plugin`](https://www.npmjs.com/package/vite-plugin-manifest-sri) installed.

Manifest: [manifest.json](https://github.com/user-attachments/files/15745026/manifest.json)

This was from my [personal project](https://gitlab.com/net.christianto/portmafia-api) that being made with Laravel and InertiaJs, and the live view can be checked on [this link](https://portmafia-api.christianto.net/).

---
If you're okay with this feature being implemented within this project, is it okay if I send you a PR for this?

Thank you!

**Comment by mjhoy** [comment]
@chez14 definitely! PRs welcome.
